### PR TITLE
add silent mode and escript support

### PR DESCRIPTION
**Pull request by SophisticaSean**
Quick commit to add silent mode and escript support, relatively new to elixir so pardon me for any errors. I have tested this and it works fine for me without any additional configuration from a user. If they want the new features then its purely opt-in, else it will behave how it did before I altered the functionality.

### CODE REVIEW

**Comment by alanpeabody** [comment]
Thanks for the PR @SophisticaSean !!

I actually have a couple of questions:

1. How does the escript support work (eg, how would you use it)?
2. Could we use config.exs values to set the options instead of defining them in the mix file?

**Comment by SophisticaSean** [comment]
1. I've been writing a CLI in elixir and having to manually run mix escript.build is a hyper pain in the butt, opening up a iex session in one tab or tmux window etc. and having it auto build the executable is super convenient and allows me to quickly manually test/use my CLI without having to build it.

2. Definitely! I'll get working on that now.

**Comment by SophisticaSean** [comment]
neat i spelled config wrong, 10/10

**Comment by alanpeabody** [comment]
Cool, thanks!

**Pull request merged**
